config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'visitors#index'

  get '/search' => 'users#search'
  
  resources :posts, except: [:create]
  post '/posts' => 'posts#create', as: 'create_post'
  get  '/posts/:id/vote' => 'posts#vote', as:'vote_post'

  resources :users, only: [:index, :show] do
  	resources :followships, only: [:index, :destroy]
  	post '/followships' => 'followships#create', as: 'new_followship'
  	delete '/followships' => 'followships#destroy', as: 'remove_followship'
  end
end

app/models/followship.rb
class Followship < ActiveRecord::Base
  belongs_to :followee, class_name: 'User', counter_cache: :followee_count
  belongs_to :follower, class_name: 'User', counter_cache: :follower_count

  validates :followee_id, presence: true
  validates :follower_id, presence: true

  validates :followee_id, uniqueness: {scope: :follower_id}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, counter_cache: :post_count

  validates :content, presence: true
  validates :user_id, presence: true
  validates_length_of :content, maximum: 140

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :hashtags

  acts_as_votable

	# def self.search(options = {})
	# 	search_term = options.fetch(:content) {nil}
	# 	return [] if search_term.nil?
	#   where("content LIKE :term", term: "%#{search_term}%")
	#   #ILIKE is postgres only, http://stackoverflow.com/questions/19105706
	# end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    
  has_many :posts, dependent: :destroy
  
	has_many :spyings, class_name: "Followship", foreign_key: :followee_id, dependent: :destroy
	has_many :idols, class_name: "User", through: :spyings, source: :follower

	has_many :stalkers, class_name: "Followship", foreign_key: :follower_id, dependent: :destroy
	has_many :fans, class_name: "User", through: :stalkers, source: :followee

	def self.search(options = {})
		search_term = options.fetch(:name) {nil}
		return [] if search_term.nil?
	  where("name LIKE :term", term: "%#{search_term}%")
	end #ILIKE is postgres only, http://stackoverflow.com/questions/19105706

	# def number_of(method)
	# 	self.send(method).size.to_s
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def after_sign_in_path_for(resource)
	  user_path(current_user)
	end #http://stackoverflow.com/questions/6405941

end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.includes(:fans).find(params[:user_id])
    @user.fans << current_user
    redirect_to user_path(params[:user_id])
    #redirect_to request.env['HTTP_REFERER']
  end

  def index
  end

  def destroy
    @user = User.includes(:fans).find(params[:user_id])
    @user.fans.delete(current_user)
    redirect_to user_path(params[:user_id])
    #format.html { redirect_to controller: 'users', aciton: 'show', id: user_id }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:vote, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:vote, :create, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = params[:tag_id].nil? ? Post.includes(:user).last(10) : Post.includes(:user).tagged_with(ActsAsTaggableOn::Tag.find(params[:tag_id]))
  end

  

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def create
    @post = Post.new(post_params)
    hash_tags = @post.content.scan(/\B#\w*[a-zA-Z]+\w*/)  #http://erictarn.com/post/1060722347
    @post.save_cached_tag_list
    @post.tag_list.add(hash_tags)

    if @post.save
      flash.notice = "Your tweet is successfully created"
    else
      flash.alert =  "You've got some errors in your post, say, too long?" # <%= debug(params) if Rails.env.development? %>
    end
    redirect_to request.env['HTTP_REFERER']
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update #
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote    # GET /posts/:id/vote.json
      vote_count = case params[:vote]
      when 'Up'
        @post.upvote_by(current_user)
        @post.cached_votes_up
      when 'Down'
        @post.downvote_by(current_user)
        @post.cached_votes_down
      end

      respond_to do |format|
        format.html { render file: 'public/404', status: 404 }
        format.json { render json: {vote_count: vote_count}, status: 200 }
      end
  end # authorization by Devise' #before_action

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content, :user_id, :tag_list, :tag_id, :vote)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.includes(:idols).find(params[:id]) #eager loading
    @posts = Post.includes(:user).where(user_id: @user.idols.pluck(:id) + [@user.id] ).last(10)
    @hot_tags = ActsAsTaggableOn::Tag.most_used(10)
     #Get all posts from user and user's idols
    # unless @user == current_user
    #    redirect_to :back, alert: "Access denied." rescue redirect_to user_path
    # end
    #@post = Post.new #for form_for post
  end

  def search    # GET /search/term.json
    term     = params[:term]
    @results = term.nil? ? [] : User.search(name: term) + Post.tagged_with(term)
    respond_to do |format|
      format.html { render file: 'public/404', status: 404 }
      format.json { render json: @results, status: 200 }
    end
  end  # Search results get no ranking here

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def index
		@posts = Post.includes(:user).reverse_order.first(10)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# def hamlize
	# 	Haml::Engine.new( yield ).render if block_given?
	# end #http://stackoverflow.com/questions/5245432

end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	# def get_recent_tweets( options={} )
	# 	tweets_arr = options.fetch(:tweets_arr) rescue raise("PostsHelper::get_recent_tweets needs active record relations or array of tweets or posts")
	# 	how_many   = options.fetch(:how_many) { 10 }

	# 	return hamlize{ "%h3 There is no tweets." } if tweets_arr.empty?

	# 	# tweets_arr.each do |tweet|
	# 	# %p
	# 	#   =tweet.content
	# 	#   %br
	# 	#   posted at
	# 	#   = time_ago_in_words(tweet.created_at) 
	# 	#   ago by
	# 	#   = link_to(tweet.user.name, tweet.user)
	# 	# end
		
	# end

end

app/helpers/users_helper.rb
module UsersHelper
  def follow_button(options={})
    user = options.fetch(:user)
    extra_class = options.fetch(:extra_class)
    unfollow_label = options.fetch(:unfollow_label) {"Unfollow the user"}
    follow_label = options.fetch(:follow_label) {"Follow the user"}

    if current_user.idols.include?(user)
      return button_to(unfollow_label, user_remove_followship_path(user_id: user.id), method: :delete, class: "button btn " + extra_class)
    else
      return button_to(follow_label, user_new_followship_path(user_id: user.id), class: "button btn " + extra_class)
    end
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/followships/create.html.haml
%h1 Followships#create
%p Find me in app/views/followships/create.html.haml

app/views/followships/index.html.haml
- unless current_user.idols.empty? #move this block to helper?
  %h3 You are following:
  - current_user.idols.each do |idol|
    .panel
      = follow_button({user: idol, extra_class: 'btn-xs btn-info pull-left'})
      = link_to(idol.name, idol)

- else
  %h3 You are not following anybody.

%hr

- unless current_user.fans.empty? #move this block to helper
  %h3 You are followed by:
  - current_user.fans.each do |fan|
    .panel
      = follow_button({user: fan, extra_class: 'btn-xs btn-info pull-left'})
      = link_to(fan.name, fan)
      
- else
  %h3 You are not followed by anybody.

app/views/followships/new.html.haml
%h1 Followships#new
%p Find me in app/views/followships/new.html.haml

app/views/followships/show.html.haml
%h1 Followships#show
%p Find me in app/views/followships/show.html.haml

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
      = content_tag(:div, msg, id: "flash_#{name}")

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header 
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      - if user_signed_in?
        .navbar-form.text-right
          .input-group
            %input.form-control{id: "searchTerm", type: "text", placeholder: "search for user/#tag"}
            %span.input-group-btn
              %button.btn.btn-default{id: "searchButton", type: "button"}
                %span.glyphicon.glyphicon-search{alt: 'go!', 'aria-label' => 'go!'}

app/views/layouts/_navigation_links.html.haml
%li= link_to('Tweets', posts_path)
- if user_signed_in?
  %li= link_to('Edit account', edit_user_registration_path)
  %li= link_to('Sign out', destroy_user_session_path, method:'delete')
  %li= link_to('Users', users_path)
  %li= link_to('Tweets: ' + current_user.post_count.to_s, user_path(current_user))
  %li= link_to('Followers: ' + current_user.follower_count.to_s, user_followships_path(current_user))
  %li= link_to('Following: ' + current_user.followee_count.to_s, user_followships_path(current_user))

- else
  %li= link_to('Sign in', new_user_session_path(current_user))
  %li= link_to('Register', new_user_registration_path(current_user))

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Tweet Composer'
    %meta{name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Tweet Composer'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{role: "main"}
      = render 'layouts/messages'
      = yield
    #notification-area
    #myModal.modal.fade{role: "dialog"}
      .modal-dialog
        .modal-content
          .modal-header
            %button.close.glyphicon.glyphicon-remove{"data-dismiss" => "modal", type: "button"}
            %h4.modal-title Search Results
          .modal-body
            %ul.resultList
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/posts/_new.html.haml
.well
  %h2 New tweet
  = form_for(:post, url: create_post_path) do  #remote: true would need to notify user and refresh posted tweet
    - at_tag = current_user == user || user.name.nil? ? nil : "@"+user.name+" "
    = text_area_tag('post[content]', at_tag, {class: 'form-control', autofocus: true, onfocus: "this.selectionStart = this.selectionEnd = this.value.length;", width: "100%"}) #onfocus: "this.value = this.value;" in HTML options doesn't work, the above line is using jQuery http://stackoverflow.com/a/10576409
    = hidden_field_tag('post[user_id]', current_user.id)
    = submit_tag('Submit', class: "button btn btn-lg btn-info")
    %span.charCount 140

app/views/posts/_post.html.haml
.panel
  .panel-heading
    .panel-title.tweets{'data-id' =>  post.id}
      = link_to(post.content, user_path(post.user))
  .panel-body
    %button.btn.btn-default.vote{type: "button"}
      %span.glyphicon.glyphicon-thumbs-up{'data-id' => post.id}
      %span.badge{'data-id' => post.id, value: 'Up', alt: 'thumbs-up'} #{post.cached_votes_up} 
    %button.btn.btn-default.vote{type: "button"}
      %span.glyphicon.glyphicon-thumbs-down{'data-id' => post.id} 
      %span.badge{'data-id' => post.id, value: 'Down', alt: 'thumbs-down'} #{post.cached_votes_down}
    - unless post.cached_tag_list.blank?
      %strong
        = #pluralize(post.cached_tag_list.count('#'), 'Hashtag').sub(/^\d+\s/, '')+': '
        = post.cached_tag_list.count('#') > 1 ? 'Hashtags: ' : 'Hashtag: '
        =post.cached_tag_list
    \- Posted by
    = link_to(post.user.name + ",", post.user)
    = time_ago_in_words(post.created_at)
    ago.

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.container
  - @posts.each do |post|
    = render post

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/users/_result.html.haml
- if result.is_a?(User)
  %td= link_to result.name, result
- else
	%td= link_to result.user.name, result.user

app/views/users/_show_left.html.haml
.well
  %h3 User #{user.name}
  = image_tag(user.img_url, {alt: "User " + user.name + "'s picture", class: "thumbnail"})

  -if current_user == user
    %p
      Email: 
      = mail_to(user.email, nil, {type: "email"})
  %p
    User #{user.name} has posted 
    = pluralize(user.post_count, 'tweet') 
    so far.
  = follow_button({user: user, extra_class: 'btn-lg btn-info'})

.well
  - unless user.followee_count.zero? #move this block to helper
    %h4 User #{user.name} is following:
    - user.idols.each do |idol|
      .panel
        = follow_button({user: idol, extra_class: 'btn-xs btn-info pull-left'})
        = link_to(idol.name, idol)
  - else
    %h3 User #{user.name} is not following anyone.

.well
  %h4 Trending:
  - hot_tags.each do |tag|
    .panel
      = link_to(tag.name, posts_path(tag_id: tag.id))

app/views/users/_show_right.html.haml
.well

  -#This is for singed in user only

  - unless posts.empty? #move this block to helper, need to send both posts and current_user
    %h3 User #{user.name} and user's idols lastest tweets:
    - posts.reverse_each do |post|
      = render post
        
  - else
    %h3 User #{user.name} does not have any tweets.

app/views/users/_user.html.haml
%td= link_to user.name, user
/%td= mail_to user.email

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

app/views/users/search.html.haml
.container
  .row
    %h3 Search Results
    .column
      %table.table
        %tbody
          - @results.each do |result|
            %tr
              = render result

app/views/users/show.html.haml
.container-fluid
  .row
    .col-xs-4
      = render 'show_left', user: @user, hot_tags: @hot_tags #check if @user can be used instead.
    .col-xs-8
      = render 'posts/new', user: @user#, post: @post
      = render 'show_right', user: @user, posts: @posts  #check if @user can be used instead.

app/views/visitors/index.html.haml
%h3 Welcome
%p
  = link_to 'Users:', users_path
  = User.count
  registered so far, here are some latest tweets:

%hr

- unless @posts.empty? #move this block to helper
  - @posts.each do |post|
    = render post
- else
  %h3 There is no tweets.